### ISSUE TITLE
poor cli support

### ISSUE THREAD

**Issue by benkenawell** [Thinkmill/manypkg#125]
running `npx manypkg --help` throws an error that sort of lists the possible commands, but doesn't give any description of how to use any of them:

```bash 
> npx manypkg --help
☔️ error command --help not found, only check, exec, run, upgrade, npm-tag and fix exist
```

Similarly, running `--help` with any of the manypkg commands throws spawn errors:

```bash
> npx manypkg exec --help
☔️ error Error: spawn --help ENOENT
☔️ error     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
☔️ error     at onErrorNT (internal/child_process.js:469:16)
☔️ error     at processTicksAndRejections (internal/process/task_queues.js:82:21) {
☔️ error   errno: -2,
☔️ error   code: 'ENOENT',
☔️ error   syscall: 'spawn --help',
☔️ error   path: '--help',
☔️ error   spawnargs: []
☔️ error }

```

I expect a cli tool to give me basic information about itself when I run it with a --help flag; it would be great if manypkg could provide that experience!

**Comment by benkenawell** [comment]
I'd be happy to open a PR addressing my concerns.  Could I add a package to help create a command line interface, like [commander](https://www.npmjs.com/package/commander) or [yargs](https://www.npmjs.com/package/yargs)?
