### ISSUE TITLE
New check idea: DUPLICATE_PACKAGE_NAME

### ISSUE THREAD

**Issue by kachkaev** [Thinkmill/manypkg#235]
I was creating a new package in a monorepo by copying an existing one. I forgot to change the name and ended up with two workspaces having identical names. `pnpm install` did not complain, `manypkg` did not either. It’d be great to see an error (`DUPLICATE_PACKAGE_NAME`?) in this case.

Here is an MVE:
[github link WIP]

```
packages/a/package.json → "name": "a"
packages/b/package.json → "name": "b"
packages/c/package.json → "name": "a" ❗ should be "c"
```

```sh
pnpm lint:manypkg

## Recieved
☔️ success workspaces valid!

## Expected
☔️ error Workspaces at "packages/a" and "package/c" use the same name "a"
```

**Comment by kachkaev** [comment]
Side observation: I removed `"name"` from `packages/c/package.json` just to see what happens. `manypkg check` crashed:

```
☔️ error PackageJsonMissingNameError: The following package.jsons are missing the "name" field:
☔️ error packages/c/package.json
☔️ error     at validatePackages (/path/to/project/node_modules/@manypkg/get-packages/dist/manypkg-get-packages.cjs.dev.js:57:11)
☔️ error     at Object.getPackages (/path/to/project/node_modules/@manypkg/get-packages/dist/manypkg-get-packages.cjs.dev.js:35:3)
☔️ error     at async /path/to/project/node_modules/@manypkg/cli/dist/manypkg-cli.cjs.dev.js:813:7 {
☔️ error   directories: [ 'packages/c/package.json' ]
☔️ error }
```

I was expecting to see `INVALID_PACKAGE_NAME` but got the crash instead. This is a pretty niche edge case, so not a big deal. Just flagging in case if a fix can be easily done simultaneously.
